name: Spec
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Node Package
        run: npm i

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install TreeLDR
        run: |
          git clone --depth 1 --branch 0.1.1-beta https://github.com/spruceid/treeldr.git
          cd treeldr
          cargo install --path tldrc

      - name: Build Spec
        run: npm run build

      - name: Deploy Spec
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
